version: "3.9"

services:
  app:
    container_name: anomalius_app
    image: registry.gitlab.com/dudelkins/backend
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    env_file:
      - ../.env
    volumes:
      - "../cmd/3000.csv:/data/3000.csv"
    ports:
      - "10000:10000"
    networks:
      - network
    depends_on:
      postgres:
        condition: service_healthy
    stop_grace_period: 60s
    restart: unless-stopped

  postgres:
    container_name: anomalius_pg
    image: postgres:15rc2-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: anomalius
    volumes:
      - "${PWD}/postgres/data:/var/lib/postgresql/data"
    networks:
      - network
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

networks:
  network:
    driver: bridge
